### ISSUE TITLE
Flexible sections adheres to maxsections limit

### ISSUE THREAD

**Issue by mmulrthelp** [marinaglancy/moodle-format_flexsections#20]
Could you possibly consider allow a maxsections limit override in format_flexsections ?

Changing our global site setting to greater than 52 for the case of flexsection courses isnt really an option for us as then academics have the ability to create beasts of courses with the scroll of death on them.

**Comment by jboulen** [comment]
Hello,

Since we upgraded our Moodle to 3.11, our users have the same problem.

What is the best approach to solve this problem ?
- override the `get_max_sections()` function in `lib.php` to always return 1 + the current number of sections in the course ; so users will be always able to create any number of section with flexsections format ?
- create a new setting to allow each administrator to define a specific value for flexsections format ?

Regards,

**Comment by marinaglancy** [comment]
Hello, in the v4.0.4 (released today) I have changed it so that the maxsections limit only affects the number of sections on the top level. The number of the subsections can be unlimited.

Is this a suitable solution?
