### ISSUE TITLE
before_footer callback warning in 4.4

### ISSUE THREAD

**Issue by thepurpleblob** [marinaglancy/moodle-format_flexsections#84]
```
Callback before_footer in format_flexsections component should be migrated to new hook callback for core\hook\output\before_footer_html_generation
line 7456 of /lib/moodlelib.php: call to debugging()
line 7573 of /lib/moodlelib.php: call to {closure}()
line 71 of /lib/classes/hook/output/before_footer_html_generation.php: call to get_plugins_with_function()
line 1494 of /lib/outputrenderers.php: call to core\hook\output\before_footer_html_generation->process_legacy_callbacks()
line 555 of /lib/outputrenderers.php: call to core_renderer->footer()
line 181 of /admin/renderer.php: call to plugin_renderer_base->__call()
line 574 of /admin/index.php: call to core_admin_renderer->upgrade_environment_page()
```

**Comment by marinaglancy** [comment]
Hello, there are many more problems on 4.4, not just this debugging message. Currently 4.4 is not supported but I'm working on a new version that will be compatible with Moodle 4.4

**Comment by marinaglancy** [comment]
I'm going to close this issue because there is another open issue https://github.com/marinaglancy/moodle-format_flexsections/issues/83 about Moodle 4.4 support.

I also want to remind you that in Moodle 4.4 the core course format supports subsections. Plugin format_flexsections will soon be not needed, please consider migrating to the core format
